['0', '1', '0', '1', '1', '1', '1']
['1', '0', '1', '1', '0', '1', '0']
['1', '1', '0', '0', '0', '0', '0']
['1', '0', '1', '1', '0', '0', '0']
['1', '1', '1', '1', '0', '0', '0']
['1', '1', '1', '0', '1', '0', '1']
['1', '1', '1', '0', '1', '0', '0']
['1', '0', '1', '0', '1', '0', '0']
['0', '0', '0', '0', '1', '1', '1']
['1', '1', '0', '1', '0', '1', '1']
['0', '0', '1', '0', '1', '0', '1']
['0', '0', '1', '0', '1', '0', '0']
['0', '0', '0', '1', '1', '0', '1']
['0', '0', '0', '0', '1', '0', '0']
['1', '0', '1', '1', '0', '0', '0']
['0', '1', '1', '0', '1', '0', '0']
['0', '1', '0', '0', '1', '1', '1']
['1', '1', '0', '1', '1', '1', '1']
['1', '1', '1', '1', '1', '1', '0']
['0', '1', '0', '1', '0', '1', '1']
['0', '0', '1', '0', '1', '1', '1']
['1', '0', '0', '1', '0', '1', '0']
['1', '0', '1', '0', '1', '1', '1']
['0', '0', '0', '0', '1', '0', '1']
['1', '0', '0', '0', '0', '1', '0']
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    main()
  File "main.py", line 14, in main
    ui = GraphicalInterface(args.port, args.machine)
  File "/home/adrien/Epitech/Tek2/Semestre4/Systeme_Unix/PSU_zappy_2017/client/server/graphicalInterface.py", line 69, in __init__
    self.manageConnection()
  File "/home/adrien/Epitech/Tek2/Semestre4/Systeme_Unix/PSU_zappy_2017/client/server/graphicalInterface.py", line 390, in manageConnection
    self.teams.append(cmd.split(' ')[1:][0])
IndexError: list index out of range
